---
- hosts: all
  tasks:
    - name: install packages
      become: true
      become_method: sudo
      ansible.builtin.apt:
        state: present
        name:
          - rsyslog
          - parted