---
- name: Install Basic Packages
  hosts: all
  become: true
  become_method: sudo
  
  tasks:
    - name: Upgrade package cache
      apt:
        update_cache: yes
        
    - name: Install packages
      apt:
        autoclean: yes
        state: present
        name:
          - rsyslog
          - nano
          - parted
          - ncdu 
          - dfrs 
          - net-tools 
          - wget 
          - curl 
          - htop 
          - ncdu 
          - fd-find 
          - duf 
          - exa