---
- name: Set Message of the Day
  hosts: all
  become: true
  become_method: sudo
  
  tasks:
    - name: "copy motd file to /etc/motd"
      copy:
        src: motd.j2
        dest: /etc/motd
        owner: root
        group: root
        mode: '644'