- name: Configure Daily Security Updates (Debian)
  hosts: all
  become: true
  become_method: sudo 
#  gather_facts: false
  
  tasks:
  
#    - name: Install apt prerequisites for automated reboots
#      ansible.builtin.apt:
#        state: present
#        name: 
#          - unattended-upgrades
#          - apt-listchanges

 #   - name: "copy config file 1"
 #     template:
 #       src: setUnattendedUpgrades_50unattended-upgrades.tmpl
 #       dest: /etc/apt/apt.conf.d/50unattended-upgrades
 #       owner: root
 #       group: root
 #       mode: '644'
 #     register: unattended_upgrades_config_set

 #   - name: "copy config file 2"
 #     template:
 #       src: setUnattendedUpgrades_20auto-upgrades.tmpl
 #       dest: /etc/apt/apt.conf.d/20auto-upgrades
 #       owner: root
 #       group: root
 #       mode: '644'
 #     register: unattended_upgrades_settings_set

    - name: Dpkg reconfigure
      ansible.builtin.command:
        cmd: dpkg-reconfigure -f noninteractive unattended-upgrades
      register: dpkg_reconfigure_unattended_upgrades
      when:
        - unattended_upgrades_config_set.changed or
          unattended_upgrades_settings_set.changed